version: "3.8"

services:
  flask:
    build: .
    container_name: student-flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: StudentDB
    restart: always

  mysql:
    image: mysql:8.0
    container_name: student-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword    # required for root
      MYSQL_DATABASE: StudentDB            # optional initial DB
    ports:
      - "3306:3306"
